version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/api-to-html
    steps:
      - checkout
      - run:
          name: Download EpochTalk
          command: |
            wget https://github.com/epochtalk/epochtalk/archive/master.zip
            unzip master.zip
      - run:
          name: Install Dependencies
          command: npm install
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # set env for epochtalk path (unzipped dir)
              echo "EPOCHTALK_PATH=epochtalk-master" > .env
              node .
              # push to S3
              aws s3 cp api.html $S3_URI --region $S3_REGION
            fi
